- maven-jxr-plugin/src/main/resources/jxr-report_el.properties
Added jxr-report_el.properties that contains Greek translation
> Greek translation of jxr-report.properties

- maven-jxr-plugin/src/main/java/org/apache/maven/plugin/jxr/JxrReportUtil.java
> remove reference to deprecated class

- pom.xml
> [JXR-148] update plexus

- maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/AggregateSubmodule1MavenProjectStub.java
- maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/AggregateSubmodule2MavenProjectStub.java
- maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/AggregateTestMavenProjectStub.java
- maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/DefaultConfigurationMavenProjectStub.java
- maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/ExcludeConfigurationMavenProjectStub.java
- maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/IncludeConfigurationMavenProjectStub.java
- maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/NoJavadocDirMavenProjectStub.java
- maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/NoJavadocLinkConfigurationMavenProjectStub.java
- maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/PomMavenProjectStub.java
- maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/TestSourceDirMavenProjectStub.java
- maven-jxr/src/test/java/org/apache/maven/jxr/pacman/JavaFileImplTest.java
> fix a few generics warnings

- pom.xml
> [JXR-149] update JUnit

- .gitignore
> ignore Eclipse .checkstyle

- maven-jxr-plugin/pom.xml
@hboutemy sitetools are proving a little trickier here but we can easily do this much
> [JXR-147] update doxia

- maven-jxr/pom.xml
- maven-jxr/src/main/java/org/apache/maven/jxr/JavaCodeTransform.java
> [JXR-151] update commons lang

- maven-jxr/pom.xml
> [JXR-148] remove unused dependency

- maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/AggregateTestMavenProjectStub.java
- maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/DefaultConfigurationMavenProjectStub.java
- maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/stubs/ExcludeConfigurationMavenProjectStub.java
> remove unused imports

- maven-jxr-plugin/src/main/java/org/apache/maven/plugin/jxr/JxrReport.java
- maven-jxr-plugin/src/main/java/org/apache/maven/plugin/jxr/JxrTestReport.java
- maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/JxrReportTest.java
> [JXR-153] use locales for string comparison

- maven-jxr/pom.xml
- maven-jxr/src/test/java/org/apache/maven/jxr/JavaCodeTransformTest.java
> tidy up test dependencies

- maven-jxr-plugin/src/main/java/org/apache/maven/plugin/jxr/JxrNoForkReport.java
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
> (doc) Fix goal's description

- maven-jxr-plugin/src/site/apt/index.apt
> (doc) Fix misspelling of 'XXX-no-fork' goals

- maven-jxr-plugin/src/it/aggregate/pom.xml
- maven-jxr-plugin/src/it/mixed-plugin-report/pom.xml
- maven-jxr-plugin/src/it/new-site-config/pom.xml
- pom.xml
Upgrade maven-javadoc-plugin to 3.3.1 for integration tests to run correctly on Java 11
Upgrade sitePluginVersion 3.9.1 for integration tests to run correctly on Java 11
Move reporting outside of maven-site-plugin in order to work on latest site plugin version
If your pull request is …
> JXR-162: Upgrade minimum Java version to 8

- maven-jxr-plugin/pom.xml
- maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/JxrReportTest.java
- maven-jxr/pom.xml
- maven-jxr/src/main/java/org/apache/maven/jxr/JavaCodeTransform.java
- maven-jxr/src/test/java/org/apache/maven/jxr/DirectoryIndexerTest.java
- maven-jxr/src/test/java/org/apache/maven/jxr/IncludeExcludeTest.java
- maven-jxr/src/test/java/org/apache/maven/jxr/JavaCodeTransformTest.java
- pom.xml
> [JXR-162] Upgrade plugins to Java 8

- maven-jxr-plugin/pom.xml
- pom.xml
> [JXR-163] Require Maven 3.2.5

- maven-jxr/src/main/java/org/apache/maven/jxr/JavaCodeTransform.java
- maven-jxr/src/main/java/org/apache/maven/jxr/pacman/JavaFile.java
- maven-jxr/src/main/java/org/apache/maven/jxr/pacman/JavaFileImpl.java
- maven-jxr/src/test/java/org/apache/maven/jxr/JavaCodeTransformTest.java
- maven-jxr/src/test/resources/UnknownType.java
> [JXR-164] Use file name without path for page title

- maven-jxr-plugin/pom.xml
> [JXR-165] Upgrade Maven Reporting to 3.1.0

- maven-jxr-plugin/pom.xml
- pom.xml
> [JXR-167] Upgrade Parent to 35

- maven-jxr-plugin/pom.xml
- maven-jxr-plugin/src/test/java/org/apache/maven/plugin/jxr/JxrReportTest.java
- maven-jxr/pom.xml
- pom.xml
- use dependencyManagment if defined
- reorder dependencies
- follow convention for poms tag order
--- …
> [JXR-168] poms cleanup

- maven-jxr/pom.xml
- pom.xml
Downgrade to Velocity 1.7 to be consistent with Doxia Sitetools 1.11.1.
This closes #67
please ask on the …
> [JXR-174] Revert JXR-157 until next major version

- maven-jxr-plugin/pom.xml
- maven-jxr/pom.xml
- pom.xml
> Doxia 2.0.0 ga

- src/site/xdoc/download.xml.vm
> [JXR-182] Refresh download page
